apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: UserService
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  selector:
    matchLabels:
      app: UserService
  replicas: 2
  template:
    metadata:
      labels:
        app: UserService
    spec:
      containers:
        - name: user-service
          image: $ECR_IMAGE_NAME:$IMAGE_TAG
          ports:
            - containerPort: 8080
